# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('bojects', django.db.models.manager.Manager()),
            ],
        ),
    ]
