# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20170125_0049'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
